[workspace]

members = [
    "hello-world/program",
    "hello-world/cli",
    "hello-world-struct/program",
    "hello-world-notebook/program",
    "solana-program-part2/compare-ts-rust/cli"
]
exclude = []
