[features]
seeds = false
skip-lint = false
[programs.localnet]
helloworld = "Dwwno9cpgrbXFFEdJhMt9FB9TJKnJ5en31y433M11oPQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/roy/.config/solana/id.json"


[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

