[features]
seeds = false
skip-lint = false
[programs.localnet]
mint_token_info_anchor = "2xLs4UB4c5McNeKGiS5BPzL6MbedeQMfhu3YgFGtnn9T"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/roy/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
